name: generate report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    #Download/create
    CoverageReport:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: show content
          run: |
            pwd
            ls -la || true
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: coverage
